from . import product_template
from . import res_users
from . import res_partner
from . import hr_employee
from . import sale_order
from . import account_invoice
from . import pos_category
from . import account_tax
from . import product_category
from . import res_config_settings
from . import stock_move